### ISSUE TITLE
Spirit box addition

### ISSUE THREAD

**Issue by AeonLucid** [azsry/phasmophobia_mechanics#1]
About the [Spirit box](https://github.com/azsry/phasmophobia_mechanics#spirit-box), when playing solo I believe it is open mic as well.
It's a bit annoying to read this if statement.

```csharp
if (!this.isOn || this.soundSource.isPlaying || !XRDevice.isPresent && PlayerPrefs.GetInt("localPushToTalkValue") == 0 && (PhotonNetwork.room.PlayerCount > 1 && !GameController.instance.myPlayer.player.pcPushToTalk.isPressingPushToTalk) || GameController.instance.myPlayer.player.isDead)
```

**Comment by AeonLucid** [comment]
Also might be useful to add that insurance is 1/2th of the total item cost in amateur difficulty and 1/4th with intermediate. For the other difficulties there is no insurance.

**Comment by azsry** [comment]
> About the [Spirit box](https://github.com/azsry/phasmophobia_mechanics#spirit-box), when playing solo I believe it is open mic as well.
> It's a bit annoying to read this if statement.
> 
> ```cs
> if (!this.isOn || this.soundSource.isPlaying || !XRDevice.isPresent && PlayerPrefs.GetInt("localPushToTalkValue") == 0 && (PhotonNetwork.room.PlayerCount > 1 && !GameController.instance.myPlayer.player.pcPushToTalk.isPressingPushToTalk) || GameController.instance.myPlayer.player.isDead)
> ```

Yeah, I've updated the Spirit Box section to fix this error.
I'll add in the part about insurance. Thanks!
