### ISSUE TITLE
Contributing changes to Beta Builds

### ISSUE THREAD

**Issue by Mythra** [azsry/phasmophobia_mechanics#14]
Hey Excellent Dump Information!

I've been archiving beta builds of the game, and peering into them. Obviously some things have changed since the inception of this guide, and I'd like to start documenting them as going through IL2CPP (esp with some now obfuscated symbol names using unicode) it's generally not the most user feasible, and I'd like to make the info available for those who want it.

How would you feel about changing the branch structure to include a "stable" branch, and a "beta" branch to this repository, making stable the default people see? People like myself who poke around on beta's could then contribute documentation to the beta branch through PRs, and it could be available to those who want it.

**Comment by azsry** [comment]
Hey, I like this idea. I'll set that up for you guys :) I've stepped away from the game for the time being, so most of the word will have to be done by others. I can just be here to maintain the repo.

**Comment by Mythra** [comment]
Hey, thanks so much!

Perhaps it'd also be worthwhile to add some collaborators to approve PRs, so that way it's not on all you too?

**Comment by bermudalocket** [comment]
> Hey Excellent Dump Information!
> 
> I've been archiving beta builds of the game, and peering into them. Obviously some things have changed since the inception of this guide, and I'd like to start documenting them as going through IL2CPP (esp with some now obfuscated symbol names using unicode) it's generally not the most user feasible, and I'd like to make the info available for those who want it.
> 
> How would you feel about changing the branch structure to include a "stable" branch, and a "beta" branch to this repository, making stable the default people see? People like myself who poke around on beta's could then contribute documentation to the beta branch through PRs, and it could be available to those who want it.

Have you had any luck deobfuscating the beta branch? I can get a dump but almost everything is obfuscated and/or missing a method body entirely.

**Comment by Mythra** [comment]
Hey, the reversing process is quite a bit different for il2cpp. You can't get the raw source code, but reversing the assembly is possible. Also yes the method names are obfuscated but not particularly well.

I've been getting lots of info from the beta, I just haven't been able to contribute yet as I wanna do one full guide for a beta as to not overwhelm our maintainer with a bunch of small PRs. Unfortunately the builds change enough and are released fast enough I haven't had time to do a full doc. Part of why I'd like to see more maintainers. If you have any specific questions though I'd be happy to answer. I generally sit in the phasmo speedrunning discord. You can just ping me in the code channel.

**Comment by azsry** [comment]
@Mythra I've added you as a Collaborator, so you should be able to push to the beta branch now!

Also, once you've opened a PR, it will track all new commits since the last commit on this branch, so everything you do will be contained in that one PR until it's merged here.

The new ghost mechanics have gotten me interested in the game again. I'll also try snooping around the assembly to see what I can find.

**Comment by Mythra** [comment]
Oh wow thanks! I'll start messing with the latest beta build, since I assume that's what you pulled down. I do have the old beta builds you do to. I'll start going piece by piece I guess from the top, if there's any particular section you wanna do happy to let you review those.
