### ISSUE TITLE
Updates?

### ISSUE THREAD

**Issue by AshtonSparx** [azsry/phasmophobia_mechanics#19]
Will there be updates to this github as mechanics are tweaked/added? If so, how often will this take place? Because it's super useful.

**Comment by Mythra** [comment]
They definitely will, I was originally hoping to keep pace with beta's but tbh betas move very fast right now with the release coming soon so I've just been stockpiling notes. But when they hit stable I imagine the guide getting updates for sure when it's not trying to hit a moving target.

**Comment by AshtonSparx** [comment]
I wouldn't expect Beta's to be kept track of since, like you mentioned, they move too fast but I hope main builds will be kept track of <3

**Comment by Mythra** [comment]
Hey @AshtonSparx we've started the updates for 0.3, catching the big things, but there's still more to do. I'm gonna close this issue now, but feel free to re-open if there are any concerns!
